// Problem: CF 1812 H - Expected Twist
// https://codeforces.com/contest/1812/problem/H

/*
Algorithm: Reverse-engineering the MT19937 PRNG to recover the original array values
Techniques: 
- MT19937 tempering inverse
- Random number generator state recovery
- Query-based minimum value discovery

Time Complexity: O(n) where n is the input size. The recovery of the internal state takes constant time (624 iterations), and computing the minimum is linear in n.
Space Complexity: O(n) for storing the recovered array values.

This solution uses the fact that the values in the array are generated by a MT19937 PRNG, which can be reverse-engineered if we can get 624 consecutive outputs from it. Once the internal state is recovered, we can regenerate the rest of the sequence, and then compute the minimum directly.
*/

#define private public
#include <iostream>
#include <random>
#include <vector>
#include <algorithm>

using namespace std;
#define mod 1000000007
unsigned u = 11, d = 0xffffffffUL, s = 7, b = 0x9d2c5680UL, t = 15,
         c = 0xefc60000UL, l = 18;
unsigned untemper(unsigned z) {
  unsigned y1 = z ^ (z >> l);
  unsigned y2 = y1 ^ ((y1 << t) & c);
  unsigned sm = (1 << s) - 1;
  unsigned y3 = y2 ^ ((y2 << s) & b & (sm << s));
  unsigned y4 = y3 ^ ((y3 << s) & b & (sm << (s * 2)));
  unsigned y5 = y4 ^ ((y4 << s) & b & (sm << (s * 3)));
  unsigned y6 = y5 ^ ((y5 << s) & b & (sm << (s * 4)));
  unsigned um = (1 << u) - 1;
  unsigned y7 = y6 ^ ((y6 >> u) & (um << (u * 2)));
  unsigned y8 = y7 ^ ((y7 >> u) & (um << u));
  unsigned x = y8 ^ ((y8 >> u) & um);
  return x;
}
int main() {
  int n;
  cin >> n;
  vector<unsigned> v;
  // Query first min(624, n) elements to get outputs from MT19937
  for (int i = 0; i < min(624, n); i++) {
    cout << "? " << (i + 1) << " " << (i + 1) << endl;
    unsigned x;
    cin >> x;
    v.push_back(x);
  }
  // Initialize MT19937 with a fixed seed and set its internal state
  mt19937 rng(428);
  rng._M_p = 624;
  for (int i = 0; i < 624; i++) {
    rng._M_x[i] = untemper(v[i]);  // Reconstruct the internal state of MT19937 using untempering
  }
  // Generate additional values using the reconstructed PRNG
  for (int i = 624; i < n; i++) {
    v.push_back(rng());
  }
  // Find and output the minimum value in the recovered array
  unsigned mn = v[0];
  for (int i = 1; i < n; i++) {
    mn = min(mn, v[i]);
  }
  cout << "! " << mn << endl;
  return 0;
}


// https://github.com/VaHiX/CodeForces/