// Problem: CF 768 B - Code For 1
// https://codeforces.com/contest/768/problem/B

/*
 * Code Purpose:
 *   This program computes the number of 1s in a specific range [l, r] of a sequence
 *   generated by recursively splitting numbers > 1 into their binary representation.
 *   The process starts with a single number 'n' and each step replaces an element x > 1
 *   with x/2 and x%2 (in that order), mimicking a binary tree expansion.
 *
 *   Algorithm:
 *   - Use a recursive function to traverse the binary tree structure of the list
 *     generated by the operations.
 *   - At each step, determine how many 1s are in the range [l, r] by traversing
 *     left and right subtrees appropriately.
 *   - The root of the binary tree has 2^k elements where k is minimal such that 2^k >= n.
 *
 *   Time Complexity: O(log n)
 *   Space Complexity: O(log n) due to recursion depth
 */

#include <cstdio>
typedef long long ll;

// Recursive function to count 1s in range [x, y] within a segment of size [lower, upper]
// 'n' is current value at this node in the binary tree
ll count(ll n, ll x, ll y, ll lower, ll upper) {
  // Base case: if current segment doesn't overlap with query range [x, y], return 0
  if ((y < lower) || (x > upper) || (n == 0)) {
    return 0;
  }
  // If current node's value is 1, then it contributes 1 to count
  if (n == 1) {
    return 1;
  }
  // Compute the midpoint of current segment
  ll mid = (lower + upper) / 2;
  // Split the node into left and right child segments
  // and recursively count 1s in both parts
  // Left child: n/2, range [lower, mid-1]
  // Middle node (current): n%2, range [mid, mid]
  // Right child: n/2, range [mid+1, upper]
  return count(n / 2, x, y, lower, mid - 1) + 
         count(n % 2, x, y, mid, mid) +
         count(n / 2, x, y, mid + 1, upper);
}

int main() {
  ll n, l, r;
  scanf("%lld %lld %lld", &n, &l, &r);
  
  // Find the smallest power of 2 that is >= n to determine the size of the final list
  ll maxn = 1;
  while (maxn <= n) {
    maxn *= 2;
  }
  
  // Call recursive counting function and print result
  printf("%lld\n", count(n, l, r, 1, maxn));
  return 0;
}


// https://github.com/VaHiX/CodeForces/