// Problem: CF 745 A - Hongcow Learns the Cyclic Shift
// https://codeforces.com/contest/745/problem/A

/*
Purpose: This program determines the number of distinct strings that can be generated by performing cyclic shifts on a given string. A cyclic shift moves the last character of the string to the beginning.

Algorithm/Techniques: 
- Use a map to track distinct strings generated through cyclic shifts.
- Perform cyclic shifts iteratively by taking the last character and appending it to the front.
- Stop when all possible rotations are considered (equal to the length of the string).
- Time Complexity: O(n^2) where n is the length of the string due to string operations and map lookups.
- Space Complexity: O(n^2) for storing all unique rotations in the map.

*/

#include <iostream>
#include <map>
#include <string>

typedef long long int ll;
#define pp pair<ll, ll>
#define max2(a, b) ((a < b) ? b : a)
#define max3(a, b, c) max2(max2(a, b), c)
#define min2(a, b) ((a > b) ? b : a)
#define min3(a, b, c) min2(min2(a, b), c)
using namespace std;

int main() {
  ll i, j, k;
  ll count = 0;
  char ch;
  string s, t;
  cin >> s;
  map<string, int> ss; // Map to store unique rotations
  k = s.length() - 1;
  for (i = 0; i < s.length(); i++) {
    if (ss[s] == 0) { // Check if current string is not already seen
      ss[s]++; // Mark as seen
      count++; // Increment count of unique strings
    }
    t = s.back(); // Take last character
    s.pop_back(); // Remove last character from s
    t.append(s); // Append the remaining string to the last character
    s = t; // Update s to the new rotated string
  }
  cout << count;
  return 0;
}


// https://github.com/VaHiX/CodeForces/