// Problem: CF 1838 A - Blackboard List
// https://codeforces.com/contest/1838/problem/A

/*
Purpose: This program recovers one of the two initial integers written on a blackboard,
         given the final shuffled list of integers after repeatedly taking absolute differences.

Algorithm:
- For each test case, we process the list of integers to determine the initial two numbers.
- Key insight: the final list contains all integers generated by repeatedly taking absolute differences.
- The maximum value in the list must be one of the original two numbers.
- If there's a negative number, it must also be part of the original pair.
- We track the maximum value and check if there's a negative value in the input.
- Return the negative value if it exists, otherwise return the maximum value.

Time Complexity: O(n) per test case, where n is the number of elements in the list.
Space Complexity: O(1), only using a few variables for tracking.

Techniques:
- Single pass through the input list.
- Track maximum value and presence of negative value.
*/

#include <cstdio>
int main() {
  long t;
  scanf("%ld", &t);
  while (t--) {
    long n;
    scanf("%ld", &n);
    long neg(0), mx(0);
    for (long p = 0; p < n; p++) {
      long x;
      scanf("%ld", &x);
      if (x < 0) {
        neg = x;  // Store the first negative number encountered
      }
      mx = (mx > x) ? mx : x;  // Keep track of the maximum value
    }
    printf("%ld\n", (neg < 0) ? neg : mx);  // Output either the negative or the maximum
  }
}


// https://github.com/VaHiX/CodeForces/