// Problem: CF 743 B - Chloe and the sequence 
// https://codeforces.com/contest/743/problem/B

/*
 * Problem: Chloe and the sequence
 * 
 * Algorithm:
 * The sequence is generated by repeatedly appending the current sequence to itself
 * and inserting the next integer in the middle. This results in a fractal-like structure.
 * 
 * Key insight:
 * We can trace the position k back through the generations to find which number
 * it corresponds to. Each step doubles the size of the sequence, with the new element
 * inserted in the middle.
 * 
 * Time Complexity: O(log n) - since we iterate through the steps of the sequence generation
 * Space Complexity: O(1) - only using a constant amount of extra space
 */

#include <stdint.h>
#include <iostream>

int main() {
  const int64_t B = 100; // Threshold for loop termination
  int64_t n, k;
  std::cin >> n >> k;
  --k; // Convert to 0-based indexing
  
  int64_t mod(2), rem(0), res(1); // mod: current sequence length, rem: middle index, res: current number being inserted
  while (res < B) {
    if (k % mod == rem) { // If k falls at the middle position in current step
      std::cout << res << std::endl;
      break;
    }
    mod *= 2; // Double the sequence size
    rem = 2 * rem + 1; // Update the middle index (middle of the doubled sequence)
    ++res; // Move to next number to be inserted
  }
  return 0;
}


// https://github.com/VaHiX/CodeForces/